name: Test package

on: [push, pull_request]

jobs:
  build-and-test:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        laravel: [9.*, 10.*]       
        stability: [prefer-lowest, prefer-stable]           
        include: 
          - laravel: 9.*
            testbench: 7.*
            collision: 6.*
          - laravel: 10.*
            testbench: 8.*
            collision: 7.*        
                      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath

      - name: Install dependencies
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "nunomaduro/collision:${{ matrix.collision }}" --dev --no-interaction --no-update --ansi
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi

      - name: Execute tests
        run: composer test:coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: .coverage/clover.xml
          verbose: true  